services:

  data-store:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devenvironment
      MONGO_INITDB_DATABASE: dungeondb

  api:
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    restart: always
    ports:
      - "8081:80"

  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    restart: always
    ports: 
      - "80:80"

  rabbit:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"