services:

  data-store:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devenvironment
      MONGO_INITDB_DATABASE: dungeondb

  api:
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./api:/code/api
    depends_on:
      rabbit:
        condition: service_healthy
        restart: true

  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html

  rabbit:
    #image: rabbitmq:management
    build:
      context: .
      dockerfile: containers/rabbit/Dockerfile
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      # test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 3
      timeout: 30s