services:

  data-store:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devenvironment
      MONGO_INITDB_DATABASE: dungeondb

  api:
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    #image: nginx
    restart: always
    ports:
      - "8081:80"