apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: lobachevsky.net:4444/dungeon_times/dungeontimes-d-dm:latest
    command: ["sleep", "1000000"]
    # args: [""]
  restartPolicy: OnFailure